export const footerItems = [
  {
    title: "HarifBET",
    items: [
      {
        item: "About us",
        link: "#",
      },
      {
        item: "Terms and conditions",
        link: "#",
      },
      {
        item: "Affiliate program",
        link: "#",
      },
      {
        item: "become an agent",
        link: "#",
      },
      {
        item: "bet slip check",
        link: "#",
      },
      {
        item: "mobile version",
        link: "#",
      },
      {
        item: "payment methods",
        link: "#",
      },
      {
        item: "blog",
        link: "#",
      },
      {
        item: "contact methusods",
        link: "#",
      },
    ],
  },
  {
    title: "Betting",
    items: [
      {
        item: "Sports",
        link: "#",
      },
      {
        item: "Multi Live",
        link: "#",
      },
      {
        item: "Live",
        link: "#",
      },
      {
        item: "Numbers",
        link: "#",
      },
      {
        item: "Toto",
        link: "#",
      },
    ],
  },
  {
    title: "Games",
    items: [
      {
        item: "Casino",
        link: "#",
      },
      {
        item: "1XFGAMES",
        link: "#",
      },
      {
        item: "TV Games",
        link: "#",
      },
      {
        item: "Bingo",
        link: "#",
      },
      {
        item: "Bitcoin",
        link: "#",
      },
    ],
  },
  {
    title: "Statistics",
    items: [
      {
        item: "Statistics",
        link: "#",
      },
      {
        item: "Results",
        link: "#",
      },
    ],
  },
  {
    title: "Useful Links",
    items: [
      {
        item: "Terms of Service",
        link: "#",
      },
      {
        item: "Responsibilie Gaming",
        link: "#",
      },
      {
        item: "Self-Exclusion",
        link: "#",
      },
      {
        item: "Dispute Resolution",
        link: "#",
      },
      {
        item: "Anti-Money Laudering",
        link: "#",
      },
      {
        item: "Firness & RNG Testing Methods",
        link: "#",
      },
      {
        item: "KYC Policies",
        link: "#",
      },
      {
        item: "Privacy & Management of Persons",
        link: "#",
      },
      {
        item: "Accounts, Payouts & Bonuses",
        link: "#",
      },
    ],
  },
  {
    title: "Apps",
    items: [
      {
        item: "IOS",
        link: "#",
      },
      {
        item: "Android",
        link: "#",
      },
      {
        item: "Windows",
        link: "#",
      },
    ],
  },
];

export const matchesArray = [
  {
    id: 1,
    league: "English Premier League",
    countryFlagUrl: "https://via.placeholder.com/50",
    teams: "Manchester United vs. Liverpool",
    date: "2024-05-15",
    odds: [
      { value: "1", odd: "2.1" },
      { value: "X", odd: "3.25" },
      { value: "2", odd: "2.8" },
      { value: "1x", odd: "1.4" },
      { value: "12", odd: "1.6" },
      { value: "x2", odd: "1.8" },
    ],
    markets: [
      {
        marketName: "1X2",
        values: [
          { value: "W1", odd: "1.58" },
          { value: "X", odd: "5.06" },
          { value: "W2", odd: "5.48" },
        ],
      },
      {
        marketName: "Double Chance",
        values: [
          { value: "1X", odd: "2.18" },
          { value: "12", odd: "3.46" },
          { value: "2x", odd: "2.48" },
        ],
      },
      {
        marketName: "Both Teams To Score",
        values: [
          { value: "Yes", odd: "2.321" },
          { value: "No", odd: "1.43" },
        ],
      },
      {
        marketName: "Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Over 4.5", odd: "3.43" },
          { value: "Over 5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
          { value: "Under 4.5", odd: "3.43" },
          { value: "Under 5", odd: "3.33" },
        ],
      },
      {
        marketName: "Asian Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
        ],
      },
      {
        marketName: "Handicap",
        values: [
          { value: "1 (-2.5)", odd: "2.321" },
          { value: "1 (-2)", odd: "3.43" },
          { value: "1 (-1.5", odd: "3.43" },
          { value: "1 (-1)", odd: "3.43" },
          { value: "1 (0)", odd: "3.43" },
          { value: "2 (+2.5)", odd: "3.321" },
          { value: "2 (+2)", odd: "3.33" },
          { value: "2 (+1.5)", odd: "3.43" },
          { value: "2 (+1)", odd: "3.43" },
          { value: "2 (0)", odd: "3.43" },
        ],
      },
      {
        marketName: "Draw 0:0",
        values: [
          { value: "Yes", odd: "4.3" },
          { value: "No", odd: "1.23" },
        ],
      },
    ],
  },
  {
    id: 2,
    league: "Italian Serie A",
    countryFlagUrl: "https://via.placeholder.com/50",
    teams: "Juventus vs. Inter Milan",
    date: "2024-05-17",
    odds: [
      { value: "1", odd: "2.1" },
      { value: "X", odd: "3.25" },
      { value: "2", odd: "2.8" },
      { value: "1x", odd: "1.4" },
      { value: "12", odd: "1.6" },
      { value: "x2", odd: "1.8" },
    ],
    markets: [
      {
        marketName: "1X2",
        values: [
          { value: "W1", odd: "1.58" },
          { value: "X", odd: "5.06" },
          { value: "W2", odd: "5.48" },
        ],
      },
      {
        marketName: "Double Chance",
        values: [
          { value: "1X", odd: "2.18" },
          { value: "12", odd: "3.46" },
          { value: "2x", odd: "2.48" },
        ],
      },
      {
        marketName: "Both Teams To Score",
        values: [
          { value: "Yes", odd: "2.321" },
          { value: "No", odd: "1.43" },
        ],
      },
      {
        marketName: "Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Over 4.5", odd: "3.43" },
          { value: "Over 5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
          { value: "Under 4.5", odd: "3.43" },
          { value: "Under 5", odd: "3.33" },
        ],
      },
      {
        marketName: "Asian Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
        ],
      },
      {
        marketName: "Handicap",
        values: [
          { value: "1 (-2.5)", odd: "2.321" },
          { value: "1 (-2)", odd: "3.43" },
          { value: "1 (-1.5", odd: "3.43" },
          { value: "1 (-1)", odd: "3.43" },
          { value: "1 (0)", odd: "3.43" },
          { value: "2 (+2.5)", odd: "3.321" },
          { value: "2 (+2)", odd: "3.33" },
          { value: "2 (+1.5)", odd: "3.43" },
          { value: "2 (+1)", odd: "3.43" },
          { value: "2 (0)", odd: "3.43" },
        ],
      },
      {
        marketName: "Draw 0:0",
        values: [
          { value: "Yes", odd: "4.3" },
          { value: "No", odd: "1.23" },
        ],
      },
    ],
  },
  {
    id: 3,
    league: "Spanish La Liga",
    countryFlagUrl: "https://via.placeholder.com/50",
    teams: "Barcelona vs. Real Madrid",
    date: "2024-05-16",
    odds: [
      { value: "1", odd: "2.1" },
      { value: "X", odd: "3.25" },
      { value: "2", odd: "2.8" },
      { value: "1x", odd: "1.4" },
      { value: "12", odd: "1.6" },
      { value: "x2", odd: "1.8" },
    ],
    markets: [
      {
        marketName: "1X2",
        values: [
          { value: "W1", odd: "1.58" },
          { value: "X", odd: "5.06" },
          { value: "W2", odd: "5.48" },
        ],
      },
      {
        marketName: "Double Chance",
        values: [
          { value: "1X", odd: "2.18" },
          { value: "12", odd: "3.46" },
          { value: "2x", odd: "2.48" },
        ],
      },
      {
        marketName: "Both Teams To Score",
        values: [
          { value: "Yes", odd: "2.321" },
          { value: "No", odd: "1.43" },
        ],
      },
      {
        marketName: "Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Over 4.5", odd: "3.43" },
          { value: "Over 5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
          { value: "Under 4.5", odd: "3.43" },
          { value: "Under 5", odd: "3.33" },
        ],
      },
      {
        marketName: "Asian Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
        ],
      },
      {
        marketName: "Handicap",
        values: [
          { value: "1 (-2.5)", odd: "2.321" },
          { value: "1 (-2)", odd: "3.43" },
          { value: "1 (-1.5", odd: "3.43" },
          { value: "1 (-1)", odd: "3.43" },
          { value: "1 (0)", odd: "3.43" },
          { value: "2 (+2.5)", odd: "3.321" },
          { value: "2 (+2)", odd: "3.33" },
          { value: "2 (+1.5)", odd: "3.43" },
          { value: "2 (+1)", odd: "3.43" },
          { value: "2 (0)", odd: "3.43" },
        ],
      },
      {
        marketName: "Draw 0:0",
        values: [
          { value: "Yes", odd: "4.3" },
          { value: "No", odd: "1.23" },
        ],
      },
    ],
  },
  {
    id: 4,
    league: "Italian Serie A",
    countryFlagUrl: "https://via.placeholder.com/50",
    teams: "Juventus vs. Inter Milan",
    date: "2024-05-17",
    odds: [
      { value: "1", odd: "2.1" },
      { value: "X", odd: "3.25" },
      { value: "2", odd: "2.8" },
      { value: "1x", odd: "1.4" },
      { value: "12", odd: "1.6" },
      { value: "x2", odd: "1.8" },
    ],
    markets: [
      {
        marketName: "1X2",
        values: [
          { value: "W1", odd: "1.58" },
          { value: "X", odd: "5.06" },
          { value: "W2", odd: "5.48" },
        ],
      },
      {
        marketName: "Double Chance",
        values: [
          { value: "1X", odd: "2.18" },
          { value: "12", odd: "3.46" },
          { value: "2x", odd: "2.48" },
        ],
      },
      {
        marketName: "Both Teams To Score",
        values: [
          { value: "Yes", odd: "2.321" },
          { value: "No", odd: "1.43" },
        ],
      },
      {
        marketName: "Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Over 4.5", odd: "3.43" },
          { value: "Over 5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
          { value: "Under 4.5", odd: "3.43" },
          { value: "Under 5", odd: "3.33" },
        ],
      },
      {
        marketName: "Asian Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
        ],
      },
      {
        marketName: "Handicap",
        values: [
          { value: "1 (-2.5)", odd: "2.321" },
          { value: "1 (-2)", odd: "3.43" },
          { value: "1 (-1.5", odd: "3.43" },
          { value: "1 (-1)", odd: "3.43" },
          { value: "1 (0)", odd: "3.43" },
          { value: "2 (+2.5)", odd: "3.321" },
          { value: "2 (+2)", odd: "3.33" },
          { value: "2 (+1.5)", odd: "3.43" },
          { value: "2 (+1)", odd: "3.43" },
          { value: "2 (0)", odd: "3.43" },
        ],
      },
      {
        marketName: "Draw 0:0",
        values: [
          { value: "Yes", odd: "4.3" },
          { value: "No", odd: "1.23" },
        ],
      },
    ],
  },
  {
    id: 5,
    league: "Italian Serie A",
    countryFlagUrl: "https://via.placeholder.com/50",
    teams: "Juventus vs. Inter Milan",
    date: "2024-05-17",
    odds: [
      { value: "1", odd: "2.1" },
      { value: "X", odd: "3.25" },
      { value: "2", odd: "2.8" },
      { value: "1x", odd: "1.4" },
      { value: "12", odd: "1.6" },
      { value: "x2", odd: "1.8" },
    ],
    markets: [
      {
        marketName: "1X2",
        values: [
          { value: "W1", odd: "1.58" },
          { value: "X", odd: "5.06" },
          { value: "W2", odd: "5.48" },
        ],
      },
      {
        marketName: "Double Chance",
        values: [
          { value: "1X", odd: "2.18" },
          { value: "12", odd: "3.46" },
          { value: "2x", odd: "2.48" },
        ],
      },
      {
        marketName: "Both Teams To Score",
        values: [
          { value: "Yes", odd: "2.321" },
          { value: "No", odd: "1.43" },
        ],
      },
      {
        marketName: "Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Over 4.5", odd: "3.43" },
          { value: "Over 5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
          { value: "Under 4.5", odd: "3.43" },
          { value: "Under 5", odd: "3.33" },
        ],
      },
      {
        marketName: "Asian Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
        ],
      },
      {
        marketName: "Handicap",
        values: [
          { value: "1 (-2.5)", odd: "2.321" },
          { value: "1 (-2)", odd: "3.43" },
          { value: "1 (-1.5", odd: "3.43" },
          { value: "1 (-1)", odd: "3.43" },
          { value: "1 (0)", odd: "3.43" },
          { value: "2 (+2.5)", odd: "3.321" },
          { value: "2 (+2)", odd: "3.33" },
          { value: "2 (+1.5)", odd: "3.43" },
          { value: "2 (+1)", odd: "3.43" },
          { value: "2 (0)", odd: "3.43" },
        ],
      },
      {
        marketName: "Draw 0:0",
        values: [
          { value: "Yes", odd: "4.3" },
          { value: "No", odd: "1.23" },
        ],
      },
    ],
  },
  {
    id: 6,
    league: "Italian Serie A",
    countryFlagUrl: "https://via.placeholder.com/50",
    teams: "Juventus vs. Inter Milan",
    date: "2024-05-17",
    odds: [
      { value: "1", odd: "2.1" },
      { value: "X", odd: "3.25" },
      { value: "2", odd: "2.8" },
      { value: "1x", odd: "1.4" },
      { value: "12", odd: "1.6" },
      { value: "x2", odd: "1.8" },
    ],
    markets: [
      {
        marketName: "1X2",
        values: [
          { value: "W1", odd: "1.58" },
          { value: "X", odd: "5.06" },
          { value: "W2", odd: "5.48" },
        ],
      },
      {
        marketName: "Double Chance",
        values: [
          { value: "1X", odd: "2.18" },
          { value: "12", odd: "3.46" },
          { value: "2x", odd: "2.48" },
        ],
      },
      {
        marketName: "Both Teams To Score",
        values: [
          { value: "Yes", odd: "2.321" },
          { value: "No", odd: "1.43" },
        ],
      },
      {
        marketName: "Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Over 4.5", odd: "3.43" },
          { value: "Over 5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
          { value: "Under 4.5", odd: "3.43" },
          { value: "Under 5", odd: "3.33" },
        ],
      },
      {
        marketName: "Asian Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
        ],
      },
      {
        marketName: "Handicap",
        values: [
          { value: "1 (-2.5)", odd: "2.321" },
          { value: "1 (-2)", odd: "3.43" },
          { value: "1 (-1.5", odd: "3.43" },
          { value: "1 (-1)", odd: "3.43" },
          { value: "1 (0)", odd: "3.43" },
          { value: "2 (+2.5)", odd: "3.321" },
          { value: "2 (+2)", odd: "3.33" },
          { value: "2 (+1.5)", odd: "3.43" },
          { value: "2 (+1)", odd: "3.43" },
          { value: "2 (0)", odd: "3.43" },
        ],
      },
      {
        marketName: "Draw 0:0",
        values: [
          { value: "Yes", odd: "4.3" },
          { value: "No", odd: "1.23" },
        ],
      },
    ],
  },
  {
    id: 7,
    league: "English Premier League",
    countryFlagUrl: "https://via.placeholder.com/50",
    teams: "Manchester United vs. Liverpool",
    date: "2024-05-15",
    odds: [
      { value: "1", odd: "2.1" },
      { value: "X", odd: "3.25" },
      { value: "2", odd: "2.8" },
      { value: "1x", odd: "1.4" },
      { value: "12", odd: "1.6" },
      { value: "x2", odd: "1.8" },
    ],
    markets: [
      {
        marketName: "1X2",
        values: [
          { value: "W1", odd: "1.58" },
          { value: "X", odd: "5.06" },
          { value: "W2", odd: "5.48" },
        ],
      },
      {
        marketName: "Double Chance",
        values: [
          { value: "1X", odd: "2.18" },
          { value: "12", odd: "3.46" },
          { value: "2x", odd: "2.48" },
        ],
      },
      {
        marketName: "Both Teams To Score",
        values: [
          { value: "Yes", odd: "2.321" },
          { value: "No", odd: "1.43" },
        ],
      },
      {
        marketName: "Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Over 4.5", odd: "3.43" },
          { value: "Over 5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
          { value: "Under 4.5", odd: "3.43" },
          { value: "Under 5", odd: "3.33" },
        ],
      },
      {
        marketName: "Asian Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
        ],
      },
      {
        marketName: "Handicap",
        values: [
          { value: "1 (-2.5)", odd: "2.321" },
          { value: "1 (-2)", odd: "3.43" },
          { value: "1 (-1.5", odd: "3.43" },
          { value: "1 (-1)", odd: "3.43" },
          { value: "1 (0)", odd: "3.43" },
          { value: "2 (+2.5)", odd: "3.321" },
          { value: "2 (+2)", odd: "3.33" },
          { value: "2 (+1.5)", odd: "3.43" },
          { value: "2 (+1)", odd: "3.43" },
          { value: "2 (0)", odd: "3.43" },
        ],
      },
      {
        marketName: "Draw 0:0",
        values: [
          { value: "Yes", odd: "4.3" },
          { value: "No", odd: "1.23" },
        ],
      },
    ],
  },
  {
    id: 8,
    league: "Italian Serie A",
    countryFlagUrl: "https://via.placeholder.com/50",
    teams: "Juventus vs. Inter Milan",
    date: "2024-05-17",
    odds: [
      { value: "1", odd: "2.1" },
      { value: "X", odd: "3.25" },
      { value: "2", odd: "2.8" },
      { value: "1x", odd: "1.4" },
      { value: "12", odd: "1.6" },
      { value: "x2", odd: "1.8" },
    ],
    markets: [
      {
        marketName: "1X2",
        values: [
          { value: "W1", odd: "1.58" },
          { value: "X", odd: "5.06" },
          { value: "W2", odd: "5.48" },
        ],
      },
      {
        marketName: "Double Chance",
        values: [
          { value: "1X", odd: "2.18" },
          { value: "12", odd: "3.46" },
          { value: "2x", odd: "2.48" },
        ],
      },
      {
        marketName: "Both Teams To Score",
        values: [
          { value: "Yes", odd: "2.321" },
          { value: "No", odd: "1.43" },
        ],
      },
      {
        marketName: "Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Over 4.5", odd: "3.43" },
          { value: "Over 5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
          { value: "Under 4.5", odd: "3.43" },
          { value: "Under 5", odd: "3.33" },
        ],
      },
      {
        marketName: "Asian Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
        ],
      },
      {
        marketName: "Handicap",
        values: [
          { value: "1 (-2.5)", odd: "2.321" },
          { value: "1 (-2)", odd: "3.43" },
          { value: "1 (-1.5", odd: "3.43" },
          { value: "1 (-1)", odd: "3.43" },
          { value: "1 (0)", odd: "3.43" },
          { value: "2 (+2.5)", odd: "3.321" },
          { value: "2 (+2)", odd: "3.33" },
          { value: "2 (+1.5)", odd: "3.43" },
          { value: "2 (+1)", odd: "3.43" },
          { value: "2 (0)", odd: "3.43" },
        ],
      },
      {
        marketName: "Draw 0:0",
        values: [
          { value: "Yes", odd: "4.3" },
          { value: "No", odd: "1.23" },
        ],
      },
    ],
  },
  {
    id: 9,
    league: "Spanish La Liga",
    countryFlagUrl: "https://via.placeholder.com/50",
    teams: "Barcelona vs. Real Madrid",
    date: "2024-05-16",
    odds: [
      { value: "1", odd: "2.1" },
      { value: "X", odd: "3.25" },
      { value: "2", odd: "2.8" },
      { value: "1x", odd: "1.4" },
      { value: "12", odd: "1.6" },
      { value: "x2", odd: "1.8" },
    ],
    markets: [
      {
        marketName: "1X2",
        values: [
          { value: "W1", odd: "1.58" },
          { value: "X", odd: "5.06" },
          { value: "W2", odd: "5.48" },
        ],
      },
      {
        marketName: "Double Chance",
        values: [
          { value: "1X", odd: "2.18" },
          { value: "12", odd: "3.46" },
          { value: "2x", odd: "2.48" },
        ],
      },
      {
        marketName: "Both Teams To Score",
        values: [
          { value: "Yes", odd: "2.321" },
          { value: "No", odd: "1.43" },
        ],
      },
      {
        marketName: "Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Over 4.5", odd: "3.43" },
          { value: "Over 5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
          { value: "Under 4.5", odd: "3.43" },
          { value: "Under 5", odd: "3.33" },
        ],
      },
      {
        marketName: "Asian Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
        ],
      },
      {
        marketName: "Handicap",
        values: [
          { value: "1 (-2.5)", odd: "2.321" },
          { value: "1 (-2)", odd: "3.43" },
          { value: "1 (-1.5", odd: "3.43" },
          { value: "1 (-1)", odd: "3.43" },
          { value: "1 (0)", odd: "3.43" },
          { value: "2 (+2.5)", odd: "3.321" },
          { value: "2 (+2)", odd: "3.33" },
          { value: "2 (+1.5)", odd: "3.43" },
          { value: "2 (+1)", odd: "3.43" },
          { value: "2 (0)", odd: "3.43" },
        ],
      },
      {
        marketName: "Draw 0:0",
        values: [
          { value: "Yes", odd: "4.3" },
          { value: "No", odd: "1.23" },
        ],
      },
    ],
  },
  {
    id: 10,
    league: "Italian Serie A",
    countryFlagUrl: "https://via.placeholder.com/50",
    teams: "Juventus vs. Inter Milan",
    date: "2024-05-17",
    odds: [
      { value: "1", odd: "2.1" },
      { value: "X", odd: "3.25" },
      { value: "2", odd: "2.8" },
      { value: "1x", odd: "1.4" },
      { value: "12", odd: "1.6" },
      { value: "x2", odd: "1.8" },
    ],
    markets: [
      {
        marketName: "1X2",
        values: [
          { value: "W1", odd: "1.58" },
          { value: "X", odd: "5.06" },
          { value: "W2", odd: "5.48" },
        ],
      },
      {
        marketName: "Double Chance",
        values: [
          { value: "1X", odd: "2.18" },
          { value: "12", odd: "3.46" },
          { value: "2x", odd: "2.48" },
        ],
      },
      {
        marketName: "Both Teams To Score",
        values: [
          { value: "Yes", odd: "2.321" },
          { value: "No", odd: "1.43" },
        ],
      },
      {
        marketName: "Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Over 4.5", odd: "3.43" },
          { value: "Over 5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
          { value: "Under 4.5", odd: "3.43" },
          { value: "Under 5", odd: "3.33" },
        ],
      },
      {
        marketName: "Asian Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
        ],
      },
      {
        marketName: "Handicap",
        values: [
          { value: "1 (-2.5)", odd: "2.321" },
          { value: "1 (-2)", odd: "3.43" },
          { value: "1 (-1.5", odd: "3.43" },
          { value: "1 (-1)", odd: "3.43" },
          { value: "1 (0)", odd: "3.43" },
          { value: "2 (+2.5)", odd: "3.321" },
          { value: "2 (+2)", odd: "3.33" },
          { value: "2 (+1.5)", odd: "3.43" },
          { value: "2 (+1)", odd: "3.43" },
          { value: "2 (0)", odd: "3.43" },
        ],
      },
      {
        marketName: "Draw 0:0",
        values: [
          { value: "Yes", odd: "4.3" },
          { value: "No", odd: "1.23" },
        ],
      },
    ],
  },
  {
    id: 11,
    league: "Italian Serie A",
    countryFlagUrl: "https://via.placeholder.com/50",
    teams: "Juventus vs. Inter Milan",
    date: "2024-05-17",
    odds: [
      { value: "1", odd: "2.1" },
      { value: "X", odd: "3.25" },
      { value: "2", odd: "2.8" },
      { value: "1x", odd: "1.4" },
      { value: "12", odd: "1.6" },
      { value: "x2", odd: "1.8" },
    ],
    markets: [
      {
        marketName: "1X2",
        values: [
          { value: "W1", odd: "1.58" },
          { value: "X", odd: "5.06" },
          { value: "W2", odd: "5.48" },
        ],
      },
      {
        marketName: "Double Chance",
        values: [
          { value: "1X", odd: "2.18" },
          { value: "12", odd: "3.46" },
          { value: "2x", odd: "2.48" },
        ],
      },
      {
        marketName: "Both Teams To Score",
        values: [
          { value: "Yes", odd: "2.321" },
          { value: "No", odd: "1.43" },
        ],
      },
      {
        marketName: "Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Over 4.5", odd: "3.43" },
          { value: "Over 5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
          { value: "Under 4.5", odd: "3.43" },
          { value: "Under 5", odd: "3.33" },
        ],
      },
      {
        marketName: "Asian Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
        ],
      },
      {
        marketName: "Handicap",
        values: [
          { value: "1 (-2.5)", odd: "2.321" },
          { value: "1 (-2)", odd: "3.43" },
          { value: "1 (-1.5", odd: "3.43" },
          { value: "1 (-1)", odd: "3.43" },
          { value: "1 (0)", odd: "3.43" },
          { value: "2 (+2.5)", odd: "3.321" },
          { value: "2 (+2)", odd: "3.33" },
          { value: "2 (+1.5)", odd: "3.43" },
          { value: "2 (+1)", odd: "3.43" },
          { value: "2 (0)", odd: "3.43" },
        ],
      },
      {
        marketName: "Draw 0:0",
        values: [
          { value: "Yes", odd: "4.3" },
          { value: "No", odd: "1.23" },
        ],
      },
    ],
  },
  {
    id: 12,
    league: "Italian Serie A",
    countryFlagUrl: "https://via.placeholder.com/50",
    teams: "Juventus vs. Inter Milan",
    date: "2024-05-17",
    odds: [
      { value: "1", odd: "2.1" },
      { value: "X", odd: "3.25" },
      { value: "2", odd: "2.8" },
      { value: "1x", odd: "1.4" },
      { value: "12", odd: "1.6" },
      { value: "x2", odd: "1.8" },
    ],
    markets: [
      {
        marketName: "1X2",
        values: [
          { value: "W1", odd: "1.58" },
          { value: "X", odd: "5.06" },
          { value: "W2", odd: "5.48" },
        ],
      },
      {
        marketName: "Double Chance",
        values: [
          { value: "1X", odd: "2.18" },
          { value: "12", odd: "3.46" },
          { value: "2x", odd: "2.48" },
        ],
      },
      {
        marketName: "Both Teams To Score",
        values: [
          { value: "Yes", odd: "2.321" },
          { value: "No", odd: "1.43" },
        ],
      },
      {
        marketName: "Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Over 4.5", odd: "3.43" },
          { value: "Over 5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
          { value: "Under 4.5", odd: "3.43" },
          { value: "Under 5", odd: "3.33" },
        ],
      },
      {
        marketName: "Asian Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
        ],
      },
      {
        marketName: "Handicap",
        values: [
          { value: "1 (-2.5)", odd: "2.321" },
          { value: "1 (-2)", odd: "3.43" },
          { value: "1 (-1.5", odd: "3.43" },
          { value: "1 (-1)", odd: "3.43" },
          { value: "1 (0)", odd: "3.43" },
          { value: "2 (+2.5)", odd: "3.321" },
          { value: "2 (+2)", odd: "3.33" },
          { value: "2 (+1.5)", odd: "3.43" },
          { value: "2 (+1)", odd: "3.43" },
          { value: "2 (0)", odd: "3.43" },
        ],
      },
      {
        marketName: "Draw 0:0",
        values: [
          { value: "Yes", odd: "4.3" },
          { value: "No", odd: "1.23" },
        ],
      },
    ],
  },
  {
    id: 13,
    league: "English Premier League",
    countryFlagUrl: "https://via.placeholder.com/50",
    teams: "Manchester United vs. Liverpool",
    date: "2024-05-15",
    odds: [
      { value: "1", odd: "2.1" },
      { value: "X", odd: "3.25" },
      { value: "2", odd: "2.8" },
      { value: "1x", odd: "1.4" },
      { value: "12", odd: "1.6" },
      { value: "x2", odd: "1.8" },
    ],
    markets: [
      {
        marketName: "1X2",
        values: [
          { value: "W1", odd: "1.58" },
          { value: "X", odd: "5.06" },
          { value: "W2", odd: "5.48" },
        ],
      },
      {
        marketName: "Double Chance",
        values: [
          { value: "1X", odd: "2.18" },
          { value: "12", odd: "3.46" },
          { value: "2x", odd: "2.48" },
        ],
      },
      {
        marketName: "Both Teams To Score",
        values: [
          { value: "Yes", odd: "2.321" },
          { value: "No", odd: "1.43" },
        ],
      },
      {
        marketName: "Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Over 4.5", odd: "3.43" },
          { value: "Over 5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
          { value: "Under 4.5", odd: "3.43" },
          { value: "Under 5", odd: "3.33" },
        ],
      },
      {
        marketName: "Asian Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
        ],
      },
      {
        marketName: "Handicap",
        values: [
          { value: "1 (-2.5)", odd: "2.321" },
          { value: "1 (-2)", odd: "3.43" },
          { value: "1 (-1.5", odd: "3.43" },
          { value: "1 (-1)", odd: "3.43" },
          { value: "1 (0)", odd: "3.43" },
          { value: "2 (+2.5)", odd: "3.321" },
          { value: "2 (+2)", odd: "3.33" },
          { value: "2 (+1.5)", odd: "3.43" },
          { value: "2 (+1)", odd: "3.43" },
          { value: "2 (0)", odd: "3.43" },
        ],
      },
      {
        marketName: "Draw 0:0",
        values: [
          { value: "Yes", odd: "4.3" },
          { value: "No", odd: "1.23" },
        ],
      },
    ],
  },
  {
    id: 14,
    league: "Italian Serie A",
    countryFlagUrl: "https://via.placeholder.com/50",
    teams: "Juventus vs. Inter Milan",
    date: "2024-05-17",
    odds: [
      { value: "1", odd: "2.1" },
      { value: "X", odd: "3.25" },
      { value: "2", odd: "2.8" },
      { value: "1x", odd: "1.4" },
      { value: "12", odd: "1.6" },
      { value: "x2", odd: "1.8" },
    ],
    markets: [
      {
        marketName: "1X2",
        values: [
          { value: "W1", odd: "1.58" },
          { value: "X", odd: "5.06" },
          { value: "W2", odd: "5.48" },
        ],
      },
      {
        marketName: "Double Chance",
        values: [
          { value: "1X", odd: "2.18" },
          { value: "12", odd: "3.46" },
          { value: "2x", odd: "2.48" },
        ],
      },
      {
        marketName: "Both Teams To Score",
        values: [
          { value: "Yes", odd: "2.321" },
          { value: "No", odd: "1.43" },
        ],
      },
      {
        marketName: "Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Over 4.5", odd: "3.43" },
          { value: "Over 5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
          { value: "Under 4.5", odd: "3.43" },
          { value: "Under 5", odd: "3.33" },
        ],
      },
      {
        marketName: "Asian Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
        ],
      },
      {
        marketName: "Handicap",
        values: [
          { value: "1 (-2.5)", odd: "2.321" },
          { value: "1 (-2)", odd: "3.43" },
          { value: "1 (-1.5", odd: "3.43" },
          { value: "1 (-1)", odd: "3.43" },
          { value: "1 (0)", odd: "3.43" },
          { value: "2 (+2.5)", odd: "3.321" },
          { value: "2 (+2)", odd: "3.33" },
          { value: "2 (+1.5)", odd: "3.43" },
          { value: "2 (+1)", odd: "3.43" },
          { value: "2 (0)", odd: "3.43" },
        ],
      },
      {
        marketName: "Draw 0:0",
        values: [
          { value: "Yes", odd: "4.3" },
          { value: "No", odd: "1.23" },
        ],
      },
    ],
  },
  {
    id: 15,
    league: "Spanish La Liga",
    countryFlagUrl: "https://via.placeholder.com/50",
    teams: "Barcelona vs. Real Madrid",
    date: "2024-05-16",
    odds: [
      { value: "1", odd: "2.1" },
      { value: "X", odd: "3.25" },
      { value: "2", odd: "2.8" },
      { value: "1x", odd: "1.4" },
      { value: "12", odd: "1.6" },
      { value: "x2", odd: "1.8" },
    ],
    markets: [
      {
        marketName: "1X2",
        values: [
          { value: "W1", odd: "1.58" },
          { value: "X", odd: "5.06" },
          { value: "W2", odd: "5.48" },
        ],
      },
      {
        marketName: "Double Chance",
        values: [
          { value: "1X", odd: "2.18" },
          { value: "12", odd: "3.46" },
          { value: "2x", odd: "2.48" },
        ],
      },
      {
        marketName: "Both Teams To Score",
        values: [
          { value: "Yes", odd: "2.321" },
          { value: "No", odd: "1.43" },
        ],
      },
      {
        marketName: "Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Over 4.5", odd: "3.43" },
          { value: "Over 5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
          { value: "Under 4.5", odd: "3.43" },
          { value: "Under 5", odd: "3.33" },
        ],
      },
      {
        marketName: "Asian Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
        ],
      },
      {
        marketName: "Handicap",
        values: [
          { value: "1 (-2.5)", odd: "2.321" },
          { value: "1 (-2)", odd: "3.43" },
          { value: "1 (-1.5", odd: "3.43" },
          { value: "1 (-1)", odd: "3.43" },
          { value: "1 (0)", odd: "3.43" },
          { value: "2 (+2.5)", odd: "3.321" },
          { value: "2 (+2)", odd: "3.33" },
          { value: "2 (+1.5)", odd: "3.43" },
          { value: "2 (+1)", odd: "3.43" },
          { value: "2 (0)", odd: "3.43" },
        ],
      },
      {
        marketName: "Draw 0:0",
        values: [
          { value: "Yes", odd: "4.3" },
          { value: "No", odd: "1.23" },
        ],
      },
    ],
  },
  {
    id: 16,
    league: "Italian Serie A",
    countryFlagUrl: "https://via.placeholder.com/50",
    teams: "Juventus vs. Inter Milan",
    date: "2024-05-17",
    odds: [
      { value: "1", odd: "2.1" },
      { value: "X", odd: "3.25" },
      { value: "2", odd: "2.8" },
      { value: "1x", odd: "1.4" },
      { value: "12", odd: "1.6" },
      { value: "x2", odd: "1.8" },
    ],
    markets: [
      {
        marketName: "1X2",
        values: [
          { value: "W1", odd: "1.58" },
          { value: "X", odd: "5.06" },
          { value: "W2", odd: "5.48" },
        ],
      },
      {
        marketName: "Double Chance",
        values: [
          { value: "1X", odd: "2.18" },
          { value: "12", odd: "3.46" },
          { value: "2x", odd: "2.48" },
        ],
      },
      {
        marketName: "Both Teams To Score",
        values: [
          { value: "Yes", odd: "2.321" },
          { value: "No", odd: "1.43" },
        ],
      },
      {
        marketName: "Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Over 4.5", odd: "3.43" },
          { value: "Over 5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
          { value: "Under 4.5", odd: "3.43" },
          { value: "Under 5", odd: "3.33" },
        ],
      },
      {
        marketName: "Asian Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
        ],
      },
      {
        marketName: "Handicap",
        values: [
          { value: "1 (-2.5)", odd: "2.321" },
          { value: "1 (-2)", odd: "3.43" },
          { value: "1 (-1.5", odd: "3.43" },
          { value: "1 (-1)", odd: "3.43" },
          { value: "1 (0)", odd: "3.43" },
          { value: "2 (+2.5)", odd: "3.321" },
          { value: "2 (+2)", odd: "3.33" },
          { value: "2 (+1.5)", odd: "3.43" },
          { value: "2 (+1)", odd: "3.43" },
          { value: "2 (0)", odd: "3.43" },
        ],
      },
      {
        marketName: "Draw 0:0",
        values: [
          { value: "Yes", odd: "4.3" },
          { value: "No", odd: "1.23" },
        ],
      },
    ],
  },
  {
    id: 17,
    league: "Italian Serie A",
    countryFlagUrl: "https://via.placeholder.com/50",
    teams: "Juventus vs. Inter Milan",
    date: "2024-05-17",
    odds: [
      { value: "1", odd: "2.1" },
      { value: "X", odd: "3.25" },
      { value: "2", odd: "2.8" },
      { value: "1x", odd: "1.4" },
      { value: "12", odd: "1.6" },
      { value: "x2", odd: "1.8" },
    ],
    markets: [
      {
        marketName: "1X2",
        values: [
          { value: "W1", odd: "1.58" },
          { value: "X", odd: "5.06" },
          { value: "W2", odd: "5.48" },
        ],
      },
      {
        marketName: "Double Chance",
        values: [
          { value: "1X", odd: "2.18" },
          { value: "12", odd: "3.46" },
          { value: "2x", odd: "2.48" },
        ],
      },
      {
        marketName: "Both Teams To Score",
        values: [
          { value: "Yes", odd: "2.321" },
          { value: "No", odd: "1.43" },
        ],
      },
      {
        marketName: "Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Over 4.5", odd: "3.43" },
          { value: "Over 5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
          { value: "Under 4.5", odd: "3.43" },
          { value: "Under 5", odd: "3.33" },
        ],
      },
      {
        marketName: "Asian Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
        ],
      },
      {
        marketName: "Handicap",
        values: [
          { value: "1 (-2.5)", odd: "2.321" },
          { value: "1 (-2)", odd: "3.43" },
          { value: "1 (-1.5", odd: "3.43" },
          { value: "1 (-1)", odd: "3.43" },
          { value: "1 (0)", odd: "3.43" },
          { value: "2 (+2.5)", odd: "3.321" },
          { value: "2 (+2)", odd: "3.33" },
          { value: "2 (+1.5)", odd: "3.43" },
          { value: "2 (+1)", odd: "3.43" },
          { value: "2 (0)", odd: "3.43" },
        ],
      },
      {
        marketName: "Draw 0:0",
        values: [
          { value: "Yes", odd: "4.3" },
          { value: "No", odd: "1.23" },
        ],
      },
    ],
  },
  {
    id: 18,
    league: "Italian Serie A",
    countryFlagUrl: "https://via.placeholder.com/50",
    teams: "Juventus vs. Inter Milan",
    date: "2024-05-17",
    odds: [
      { value: "1", odd: "2.1" },
      { value: "X", odd: "3.25" },
      { value: "2", odd: "2.8" },
      { value: "1x", odd: "1.4" },
      { value: "12", odd: "1.6" },
      { value: "x2", odd: "1.8" },
    ],
    markets: [
      {
        marketName: "1X2",
        values: [
          { value: "W1", odd: "1.58" },
          { value: "X", odd: "5.06" },
          { value: "W2", odd: "5.48" },
        ],
      },
      {
        marketName: "Double Chance",
        values: [
          { value: "1X", odd: "2.18" },
          { value: "12", odd: "3.46" },
          { value: "2x", odd: "2.48" },
        ],
      },
      {
        marketName: "Both Teams To Score",
        values: [
          { value: "Yes", odd: "2.321" },
          { value: "No", odd: "1.43" },
        ],
      },
      {
        marketName: "Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Over 4.5", odd: "3.43" },
          { value: "Over 5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
          { value: "Under 4.5", odd: "3.43" },
          { value: "Under 5", odd: "3.33" },
        ],
      },
      {
        marketName: "Asian Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
        ],
      },
      {
        marketName: "Handicap",
        values: [
          { value: "1 (-2.5)", odd: "2.321" },
          { value: "1 (-2)", odd: "3.43" },
          { value: "1 (-1.5", odd: "3.43" },
          { value: "1 (-1)", odd: "3.43" },
          { value: "1 (0)", odd: "3.43" },
          { value: "2 (+2.5)", odd: "3.321" },
          { value: "2 (+2)", odd: "3.33" },
          { value: "2 (+1.5)", odd: "3.43" },
          { value: "2 (+1)", odd: "3.43" },
          { value: "2 (0)", odd: "3.43" },
        ],
      },
      {
        marketName: "Draw 0:0",
        values: [
          { value: "Yes", odd: "4.3" },
          { value: "No", odd: "1.23" },
        ],
      },
    ],
  },
  {
    id: 19,
    league: "English Premier League",
    countryFlagUrl: "https://via.placeholder.com/50",
    teams: "Manchester United vs. Liverpool",
    date: "2024-05-15",
    odds: [
      { value: "1", odd: "2.1" },
      { value: "X", odd: "3.25" },
      { value: "2", odd: "2.8" },
      { value: "1x", odd: "1.4" },
      { value: "12", odd: "1.6" },
      { value: "x2", odd: "1.8" },
    ],
    markets: [
      {
        marketName: "1X2",
        values: [
          { value: "W1", odd: "1.58" },
          { value: "X", odd: "5.06" },
          { value: "W2", odd: "5.48" },
        ],
      },
      {
        marketName: "Double Chance",
        values: [
          { value: "1X", odd: "2.18" },
          { value: "12", odd: "3.46" },
          { value: "2x", odd: "2.48" },
        ],
      },
      {
        marketName: "Both Teams To Score",
        values: [
          { value: "Yes", odd: "2.321" },
          { value: "No", odd: "1.43" },
        ],
      },
      {
        marketName: "Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Over 4.5", odd: "3.43" },
          { value: "Over 5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
          { value: "Under 4.5", odd: "3.43" },
          { value: "Under 5", odd: "3.33" },
        ],
      },
      {
        marketName: "Asian Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
        ],
      },
      {
        marketName: "Handicap",
        values: [
          { value: "1 (-2.5)", odd: "2.321" },
          { value: "1 (-2)", odd: "3.43" },
          { value: "1 (-1.5", odd: "3.43" },
          { value: "1 (-1)", odd: "3.43" },
          { value: "1 (0)", odd: "3.43" },
          { value: "2 (+2.5)", odd: "3.321" },
          { value: "2 (+2)", odd: "3.33" },
          { value: "2 (+1.5)", odd: "3.43" },
          { value: "2 (+1)", odd: "3.43" },
          { value: "2 (0)", odd: "3.43" },
        ],
      },
      {
        marketName: "Draw 0:0",
        values: [
          { value: "Yes", odd: "4.3" },
          { value: "No", odd: "1.23" },
        ],
      },
    ],
  },
  {
    id: 20,
    league: "Italian Serie A",
    countryFlagUrl: "https://via.placeholder.com/50",
    teams: "Juventus vs. Inter Milan",
    date: "2024-05-17",
    odds: [
      { value: "1", odd: "2.1" },
      { value: "X", odd: "3.25" },
      { value: "2", odd: "2.8" },
      { value: "1x", odd: "1.4" },
      { value: "12", odd: "1.6" },
      { value: "x2", odd: "1.8" },
    ],
    markets: [
      {
        marketName: "1X2",
        values: [
          { value: "W1", odd: "1.58" },
          { value: "X", odd: "5.06" },
          { value: "W2", odd: "5.48" },
        ],
      },
      {
        marketName: "Double Chance",
        values: [
          { value: "1X", odd: "2.18" },
          { value: "12", odd: "3.46" },
          { value: "2x", odd: "2.48" },
        ],
      },
      {
        marketName: "Both Teams To Score",
        values: [
          { value: "Yes", odd: "2.321" },
          { value: "No", odd: "1.43" },
        ],
      },
      {
        marketName: "Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Over 4.5", odd: "3.43" },
          { value: "Over 5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
          { value: "Under 4.5", odd: "3.43" },
          { value: "Under 5", odd: "3.33" },
        ],
      },
      {
        marketName: "Asian Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
        ],
      },
      {
        marketName: "Handicap",
        values: [
          { value: "1 (-2.5)", odd: "2.321" },
          { value: "1 (-2)", odd: "3.43" },
          { value: "1 (-1.5", odd: "3.43" },
          { value: "1 (-1)", odd: "3.43" },
          { value: "1 (0)", odd: "3.43" },
          { value: "2 (+2.5)", odd: "3.321" },
          { value: "2 (+2)", odd: "3.33" },
          { value: "2 (+1.5)", odd: "3.43" },
          { value: "2 (+1)", odd: "3.43" },
          { value: "2 (0)", odd: "3.43" },
        ],
      },
      {
        marketName: "Draw 0:0",
        values: [
          { value: "Yes", odd: "4.3" },
          { value: "No", odd: "1.23" },
        ],
      },
    ],
  },
  {
    id: 21,
    league: "Spanish La Liga",
    countryFlagUrl: "https://via.placeholder.com/50",
    teams: "Barcelona vs. Real Madrid",
    date: "2024-05-16",
    odds: [
      { value: "1", odd: "2.1" },
      { value: "X", odd: "3.25" },
      { value: "2", odd: "2.8" },
      { value: "1x", odd: "1.4" },
      { value: "12", odd: "1.6" },
      { value: "x2", odd: "1.8" },
    ],
    markets: [
      {
        marketName: "1X2",
        values: [
          { value: "W1", odd: "1.58" },
          { value: "X", odd: "5.06" },
          { value: "W2", odd: "5.48" },
        ],
      },
      {
        marketName: "Double Chance",
        values: [
          { value: "1X", odd: "2.18" },
          { value: "12", odd: "3.46" },
          { value: "2x", odd: "2.48" },
        ],
      },
      {
        marketName: "Both Teams To Score",
        values: [
          { value: "Yes", odd: "2.321" },
          { value: "No", odd: "1.43" },
        ],
      },
      {
        marketName: "Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Over 4.5", odd: "3.43" },
          { value: "Over 5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
          { value: "Under 4.5", odd: "3.43" },
          { value: "Under 5", odd: "3.33" },
        ],
      },
      {
        marketName: "Asian Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
        ],
      },
      {
        marketName: "Handicap",
        values: [
          { value: "1 (-2.5)", odd: "2.321" },
          { value: "1 (-2)", odd: "3.43" },
          { value: "1 (-1.5", odd: "3.43" },
          { value: "1 (-1)", odd: "3.43" },
          { value: "1 (0)", odd: "3.43" },
          { value: "2 (+2.5)", odd: "3.321" },
          { value: "2 (+2)", odd: "3.33" },
          { value: "2 (+1.5)", odd: "3.43" },
          { value: "2 (+1)", odd: "3.43" },
          { value: "2 (0)", odd: "3.43" },
        ],
      },
      {
        marketName: "Draw 0:0",
        values: [
          { value: "Yes", odd: "4.3" },
          { value: "No", odd: "1.23" },
        ],
      },
    ],
  },
  {
    id: 22,
    league: "Italian Serie A",
    countryFlagUrl: "https://via.placeholder.com/50",
    teams: "Juventus vs. Inter Milan",
    date: "2024-05-17",
    odds: [
      { value: "1", odd: "2.1" },
      { value: "X", odd: "3.25" },
      { value: "2", odd: "2.8" },
      { value: "1x", odd: "1.4" },
      { value: "12", odd: "1.6" },
      { value: "x2", odd: "1.8" },
    ],
    markets: [
      {
        marketName: "1X2",
        values: [
          { value: "W1", odd: "1.58" },
          { value: "X", odd: "5.06" },
          { value: "W2", odd: "5.48" },
        ],
      },
      {
        marketName: "Double Chance",
        values: [
          { value: "1X", odd: "2.18" },
          { value: "12", odd: "3.46" },
          { value: "2x", odd: "2.48" },
        ],
      },
      {
        marketName: "Both Teams To Score",
        values: [
          { value: "Yes", odd: "2.321" },
          { value: "No", odd: "1.43" },
        ],
      },
      {
        marketName: "Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Over 4.5", odd: "3.43" },
          { value: "Over 5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
          { value: "Under 4.5", odd: "3.43" },
          { value: "Under 5", odd: "3.33" },
        ],
      },
      {
        marketName: "Asian Total",
        values: [
          { value: "Over 0.5", odd: "2.321" },
          { value: "Over 1", odd: "3.43" },
          { value: "Over 1.5", odd: "3.43" },
          { value: "Over 2.5", odd: "3.43" },
          { value: "Over 3.5", odd: "3.43" },
          { value: "Under 0.5", odd: "3.321" },
          { value: "Under 1", odd: "3.33" },
          { value: "Under 1.5", odd: "3.43" },
          { value: "Under 2.5", odd: "3.43" },
          { value: "Under 3.5", odd: "3.43" },
        ],
      },
      {
        marketName: "Handicap",
        values: [
          { value: "1 (-2.5)", odd: "2.321" },
          { value: "1 (-2)", odd: "3.43" },
          { value: "1 (-1.5", odd: "3.43" },
          { value: "1 (-1)", odd: "3.43" },
          { value: "1 (0)", odd: "3.43" },
          { value: "2 (+2.5)", odd: "3.321" },
          { value: "2 (+2)", odd: "3.33" },
          { value: "2 (+1.5)", odd: "3.43" },
          { value: "2 (+1)", odd: "3.43" },
          { value: "2 (0)", odd: "3.43" },
        ],
      },
      {
        marketName: "Draw 0:0",
        values: [
          { value: "Yes", odd: "4.3" },
          { value: "No", odd: "1.23" },
        ],
      },
    ],
  },
];

export const menuOptions = [
  {
    name: "Sport",
    link: "#",
  },
  {
    name: "Live",
    link: "#",
  },
  {
    name: "Jackpot",
    link: "#",
  },
  {
    name: "Virtual Sport",
    link: "#",
  },
  {
    name: "Promotions",
    link: "#",
  },
  {
    name: " Deposit",
    link: "#",
  },
  {
    name: "Rules",
    link: "#",
  },
];

const imageUrl =
  "https://plus.unsplash.com/premium_photo-1674591173440-e559d2f73dc4?q=80&w=2070&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D";

export const filters = [
  {
    filterGroup: "SPORT",
    values: [
      { name: "Football", image: imageUrl },
      { name: "Basketball", image: imageUrl },
      { name: "Tennis", image: imageUrl },
      { name: "Futsal", image: imageUrl },
      { name: "Handball", image: imageUrl },
      { name: "Rugby", image: imageUrl },
    ],
  },
  {
    filterGroup: "COUNTRY",
    values: [
      { name: "Argentina", image: imageUrl },
      { name: "Brazil", image: imageUrl },
      { name: "Canada", image: imageUrl },
      { name: "China", image: imageUrl },
      { name: "Egypt", image: imageUrl },
      { name: "Ethiopia", image: imageUrl },
      { name: "France", image: imageUrl },
      { name: "Germany", image: imageUrl },
      { name: "India", image: imageUrl },
      { name: "Italy", image: imageUrl },
      { name: "Japan", image: imageUrl },
      { name: "Kenya", image: imageUrl },
      { name: "Mexico", image: imageUrl },
      { name: "Nigeria", image: imageUrl },
      { name: "Russia", image: imageUrl },
      { name: "South Africa", image: imageUrl },
      { name: "Spain", image: imageUrl },
      { name: "Thailand", image: imageUrl },
      { name: "United Kingdom", image: imageUrl },
      { name: "United States", image: imageUrl },
    ],
  },
  {
    filterGroup: "TOP LEAGUE",
    values: [
      { name: "English Premier League", image: imageUrl },
      { name: "French Ligue 1", image: imageUrl },
      { name: "German Bundesliga", image: imageUrl },
      { name: "Italian Serie A", image: imageUrl },
      { name: "Major League Soccer (MLS)", image: imageUrl },
      { name: "Spanish La Liga", image: imageUrl },
      { name: "Brazilian Série A", image: imageUrl },
      { name: "Dutch Eredivisie", image: imageUrl },
      { name: "Portuguese Primeira Liga", image: imageUrl },
      { name: "Russian Premier League", image: imageUrl },
    ],
  },
];
